# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jsoftwareinc
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-service-teacher
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-service-teacher

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  deploymentBucket:
    name: tmd-genai1-teacher
    blockPublicAccess: true
    serverSideEncryption: AES256

functions:
  getUser:
    handler: handler.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: get

  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users
          method: post
